### ISSUE TITLE
Psychopy install

### ISSUE THREAD

**Issue by KTZ228** [nimh-sfim/egi-pynetstation#11]
Dear developers,

I have been trying to use pynetstation with psychopy but have run into an issue I can't resolve. Apparently, psychopy's directory does not contain the ntplib module and I can't find any way of manually installing it. How could this issue be resolved?

Best, Kenneth

**Comment by jbteves** [comment]
Hi Kenneth, thanks for opening this issue! Unfortunately we're a bit stalled on getting this deployed with PsychoPy. Consider commenting [here](https://github.com/psychopy/psychopy/issues/4544) to get the attention of the PsychoPy maintainers. In the mean time, what you can do is clone the repository and move the "egi_pynetstation" directory into the "plugins" directory of your PsychoPy installation, and then removing all dots from the import statements (e.g., from .exceptions import * -> from exceptions import *).
I realize that this is wacky and convoluted but I had anticipated a faster integration time with PsychoPy, sorry about that. @pmolfese may have better insight as he has done this manual process a few times now.

**Comment by pmolfese** [comment]
Hi Kenneth-

One workaround is to copy the ntplib into the directory from the other location in PsychoPy or [download a new copy](https://github.com/remh/ntplib) and place in the pynetstation folder.  

We hope to have this more permanently solved once it's included in PsychoPy by default. 

-Peter

**Comment by pmolfese** [comment]
For reference the `egi-pynetstation` folder should exist in the python folder of psychopy. On my computer it's: `/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/egi-pynetstation`. So you would add ntplib to that folder with the rest of `egi-pynetstation`.

**Comment by KTZ228** [comment]
Thank you for your help, I only now had the time to check whether it worked. One thing that I'm confused by is that I want to use the code "from egi_pynetstation.NetStation import NetStation", but the NetStation module does not seem to be available anymore. Would I need to replace the "NetStation" in "ns = NetStation(IP_ns, port_ns)" with something?

**Comment by pmolfese** [comment]
Hi @KTZ228, I'll need some more information from you. Can you first verify that you can run the package alone without PsychoPy? 

Download the github archive and try running the example.py script:
```
git clone https://github.com/nimh-sfim/egi-pynetstation.git
cd egi-pynetstation
pip install .

python example.py amp
```

Assuming you're on a computer connected by network to the EGI amplifier and a laptop (can be the same one) with Net Station: That should initiate a connect to the amplifier, start recording (in Net Station itself) and send some events.

**Comment by KTZ228** [comment]
Thank you for your quick response. I managed to get the script working in spyder running an anaconda repository (I used pip install egi_pynetstation). I did manage to place the egi_pynetstation file into `/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/egi-pynetstation` and am able to use `import egi_pynetstation`, I'm only having trouble importing NetStation.

**Comment by pmolfese** [comment]
Ok to verify, the `example.py` script works? But now you're running into trouble getting it to run in PsychoPy3? 

Can you provide us the error message you're receiving?

**Comment by KTZ228** [comment]
Yes, `example.py` works through the Anaconda directory but not through Psychopy. 
The error I'm getting is:
```
from egi_pynetstation.NetStation import NetStation
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'egi_pynetstation.NetStation'
```

**Comment by peircej** [comment]
In PsychoPy 2022.2 egi-pynetstation is bundled into standalone. I think this issue can be closed :-)
