### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by d-scanzi** [nimh-sfim/egi-pynetstation#12]
Hi there, 

I am trying to optimize the use of PsychoPy in our lab, which has an EGI Netstation 4.5.7, to avoid the use of Eprime. I was trying to understand the major differences between your implementation and the default [egi](https://github.com/gaelen/python-egi/) package included with PsychoPy. The major questions would be: 

* *egi-pynetstation* requires Python 3 or could it be used with Python 2. Currently, the lab has an Experiment Control Computer running Windows XP, with PsycoPy 3 installed, although utilizing Python 2. 
* *egi-pynetstation* provides reliable trigger timing? I'm aware that the use of *egi* as included in PsychoPy could result in trigger-time jitter, as detailed [here](https://discourse.psychopy.org/t/egi-netstation-visual-timing-latencies/2888). 

Thank you for your work, 

Have a nice day, 

Daniele

**Comment by pmolfese** [comment]
Hi Daniele,

The major differences between this package and the "old" `egi` package are:
1) PsychoPy3 (i.e. Python 3) support
2) Utilizing the NTP timing scheme (same as E-PRIME), which is usually more accurate and has less drift than the older polling method used in the `egi` package.

It is not intended to be compatible with Python 2, though we honestly haven't tested this as pretty much everything we run is using Python 3.  The timing is accurate: On a 120Hz monitor we saw variability around 1-2ms with visual stimuli measured with a photocell over a 10 minute experiment. 

The timing should be on par with E-PRIME. Of course your mileage may vary depending on your task requirements, hardware ability, and creative coding to handle pre-loading things. 

-Peter

**Comment by d-scanzi** [comment]
Hi Peter, 

Thank you for the quick reply. I really appreciate it. I'll pass this information to the lab manager to see if we can upgrade to Python 3. 

Daniele

**Comment by pmolfese** [comment]
User will upgrade to Python 3.
